version: "3"

services:
  database:
    container_name: taxi_database
    image: postgres:13.4-alpine
    volumes:
      - taxi_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  bot:
    container_name: taxi_bot
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    command:
      - python
      - main.py
  web:
    container_name: taxi_web
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - config.wsgi:application
      - --bind
      - 0.0.0.0:8000
    env_file:
      - ./api/.env.dev
    volumes:
      - ./api/static:/app/static
  proxy:
    container_name: taxi_proxy
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./api/static:/data/static
    ports:
      - "80:80"

volumes:
  taxi_database_data:
