# Generated by Django 3.2.8 on 2021-10-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=127, verbose_name='Юзернейм телеграмм')),
                ('first_name', models.CharField(blank=True, max_length=127, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=127, verbose_name='Фамилия')),
            ],
        ),
    ]
